apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "laravel.fullname" . }}
  namespace: default
  labels:
    name: {{ template "laravel.name" . }}

data:
  # Laravel
  APP_ENV:             "local"
  APP_KEY:             "{{ .Values.appKey }}"
  APP_DEBUG:           "true"
  APP_LOG:             "errorlog"
  APP_LOG_LEVEL:       "debug"
  APP_URL:             "http://localhost"

  DB_CONNECTION:       "mysql"
  DB_HOST:             "mysql"
  DB_PORT:             "3306"
  DB_DATABASE:         "k8s_laravel"
  DB_USERNAME:         "mysql"
  DB_PASSWORD:         "my-password"

  MYSQL_PORT:          "3306"
  MYSQL_HOST:          "mysql"
  MYSQL_DATABASE:      "k8s_laravel"
  MYSQL_USER:          "root"
  MYSQL_PASSWORD:      "rootpassword"
  MYSQL_ROOT_PASSWORD: "rootpassword"

  BROADCAST_DRIVER:    "log"
  CACHE_DRIVER:        "file"
  SESSION_DRIVER:      "file"
  SESSION_LIFETIME:    "120"
  QUEUE_CONNECTION:    "sync"

  REDIS_HOST:          "myredis"
  REDIS_PASSWORD:      "null"
  REDIS_PORT:          "6379"

  AUTHY_SECRET:        "none"
  STRIPE_MODEL:        "App\\User"
  BRAINTREE_MODEL:     "App\\User"

  MAIL_DRIVER:        "smtp"
  MAIL_HOST:          "smtp.mailtrap.io"
  MAIL_PORT:          "2525"
  MAIL_USERNAME:      "af143a9a3ca0e5"
  MAIL_PASSWORD:      "7765da2cf438be"
  MAIL_FROM_ADDRESS:  "trungg@example.com"
  MAIL_FROM_NAME:     "trungg"

  # Nginx configuration
  NGINX_INCLUDE_PATH:        "/config/nginx.conf"
  NGINX_FASTCGI_GEOIP:       "on"
  NGINX_DEFAULT_SERVER:      "off"
  NGINX_PAGESPEED:           "off"
  NGINX_PAGESPEED_JS:        "off"
  NGINX_PAGESPEED_CSS:       "off"
  NGINX_PAGESPEED_IMG:       "off"
  NGINX_PAGESPEED_STORAGE:   "files"
  NGINX_PAGESPEED_REDIS:     "127.0.0.1:6379"
  NGINX_PAGESPEED_MEMCACHED: "127.0.0.1:11211"

  # PHP configuration
  PHP_UID:                   "9000"
  PHP_GID:                   "9000"
  PHP_USER:                  "php-fpm"
  PHP_HOME:                  "/app"
  PHP_POOL_PATH:             "/config/www.conf"
  PHP_CRONTABS_PATH:         "/config/artisan.crontab"
#  SUPERVISORD_PATH:          "/config/supervisord.conf"
